SELECT LINEAGE_{0}_SEQ_SCAN_0_0.in_index as lineitem_rowid_0,
       LINEAGE_{0}_ORDER_BY_4_0.out_index
FROM LINEAGE_{0}_ORDER_BY_4_0, LINEAGE_{0}_HASH_GROUP_BY_3_1,
     LINEAGE_{0}_HASH_GROUP_BY_3_0, LINEAGE_{0}_SEQ_SCAN_0_0
WHERE LINEAGE_{0}_HASH_GROUP_BY_3_1.out_index=LINEAGE_{0}_ORDER_BY_4_0.in_index
  and LINEAGE_{0}_HASH_GROUP_BY_3_1.in_index=LINEAGE_{0}_HASH_GROUP_BY_3_0.out_index
  and LINEAGE_{0}_SEQ_SCAN_0_0.out_index=LINEAGE_{0}_HASH_GROUP_BY_3_0.in_index
